branch-defaults:
  default:
    environment: front-end-dev
    group_suffix: null
  dev:
    environment: front-end-dev
    group_suffix: null
environment-defaults:
  front-end-dev:
    branch: null
    repository: null
global:
  application_name: front_end
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
